name: server_repository
description: Dart package which manages server interaction.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
