// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD76VygNypvTCoj3ZzyQfvg3e2rj2JmcKU',
    appId: '1:475156078086:web:323603d9db189a76612d87',
    messagingSenderId: '475156078086',
    projectId: 'msdcapstone-d9d54',
    authDomain: 'msdcapstone-d9d54.firebaseapp.com',
    databaseURL: 'https://msdcapstone-d9d54-default-rtdb.firebaseio.com',
    storageBucket: 'msdcapstone-d9d54.appspot.com',
    measurementId: 'G-WSBZMTH9C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCajlAHvQKywKLEOwkNr0gJC-BLiY64kiA',
    appId: '1:475156078086:android:327616d192a7f370612d87',
    messagingSenderId: '475156078086',
    projectId: 'msdcapstone-d9d54',
    databaseURL: 'https://msdcapstone-d9d54-default-rtdb.firebaseio.com',
    storageBucket: 'msdcapstone-d9d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jMMnXIx-esaasV6kwJbdj-lCW0rAxuA',
    appId: '1:475156078086:ios:a6b40cca77d9c391612d87',
    messagingSenderId: '475156078086',
    projectId: 'msdcapstone-d9d54',
    databaseURL: 'https://msdcapstone-d9d54-default-rtdb.firebaseio.com',
    storageBucket: 'msdcapstone-d9d54.appspot.com',
    iosClientId: '475156078086-telk0r06ilb4bf3ieju4jfpq3tgcrefu.apps.googleusercontent.com',
    iosBundleId: 'com.MSD.msdCapstone',
  );
}
