name: msd_capstone
description: MSD Capstone Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cached_network_image: ^3.3.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  http: ^1.1.0
  logger: ^2.0.2
  image_picker: ^1.0.4
  video_player: ^2.8.1
  flutter_staggered_grid_view: ^0.7.0
  camera: ^0.10.5+5
  stream_transform: ^2.0.0
  flow_builder: ^0.0.9
  firebase_in_app_messaging: ^0.7.4+2
  firebase_messaging: ^14.7.2
  flutter_dotenv: ^5.0.2
  mime: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.0
  mocktail: ^1.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/logos/
    - .env

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300